version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
        - ./.data/db:/var/lib/mysql
        - ./scripts/:/tmp/scripts/
        - ./db.sql:/tmp/db.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: 6e6a/docker-wordpress:latest
    links:
      - db
    ports:
      - "80:80"
    volumes:
      - ./build/:/var/www/html/wp-content/themes/
      - ./plugins/:/var/www/html/wp-content/plugins
      - ./uploads/:/var/www/html/wp-content/uploads
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    - db:db
    environment:
     - PMA_ARBITRARY=1
     - PMA_USER=wordpress
     - PMA_PASSWORD=wordpress
    restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions
